media: static/images
content:
  - name: home
    label: Startseite
    type: file
    path: content/_index.md
    format: toml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: imprint.de
    label: Impressum [DE]
    type: file
    path: content/imprint.de.md
    format: toml-frontmatter
    fields:
      - name: weight
        label: Weight
        type: number
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: imprint
    label: Impressum [EN]
    type: file
    path: content/imprint.md
    format: toml-frontmatter
    fields:
      - name: weight
        label: Weight
        type: number
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text