base_url = "https://felixschloesser.de"
title = "Felix Schlösser"
description = "A CS student currently living in Leuven, Belgium. Sometimes goes by TinTin."

default_language = "en"

build_search_index = false
compile_sass = true



[markdown]
highlight_code = true

external_links_target_blank = false
external_links_no_follow = false
external_links_no_referrer = false




[translations]
occupation = "Computer Science Student at KU Leuven"
by = "by"
source = "source"
source_code = "source code"
licenced_under = "licenced under"
content_licenced_under = "Contents, unless stated otherwise, under"
powered_by = "powered by"
zola_description = "a static site generator"
not_found_message = "Unfortunately this page could not be found."
back_to_home = "Back to the Homepage"
no_images = "No images found."

since = "since"
experience = "experience"
education = "education"

linkedin_cta = "contact on LinkedIn"
email_cta = "send email"
download_cv_pdf_cta = "download PDF"
email_subject = "job inquiry"

skills = "skills"

highlights = "highlights"
core_competencies = "core competencies"
supporting_skills = "supporting skills"
collaboration_and_leadership = "collaboration & leadership"
languages = "languages"

references = "References available upon request."


[languages.de]
# Language specific settigns
title = "Felix Schlösser"
description = "Ein Informatikstudent der derzeit in Löwen, Belgien lebt. In machen Kontexten auch als TinTin (frz. Tim von Tim und Struppi) bekannt."


[languages.de.translations]
occupation = "Informatikstudent an der KU Leuven"
by = "von"
source = "Quelle"
source_code = "Quelltext"
licenced_under = "lizensiert unter der"
content_licenced_under = "Inhalte, wenn nicht anders angegeben, unter"
powered_by = "erstellt mit"
zola_description = "einem statischen Seitengenerator"
not_found_message = "Diese Seite konnte leider nicht gefunden werden."
back = "Zurück zur Startseite"
no_images = "Keine Bilder gefunden."

since = "seit"
experience = "Erfahrungen"
education = "Bildung"
skills = "Fähigkeiten"

linkedin_cta = "Auf LinkedIn kontaktieren"
email_cta = "E-Mail senden"
download_cv_pdf_cta = "PDF herunterladen"
email_subject = "Jobanfrage"

references = "Referenzen können auf Anfrage zur Verfügung gestellt werden."

highlights = "highlights"
core_competencies = "Kernkompetenzen"
supporting_skills = "Ergänzende Fähigkeiten"
collaboration_and_leadership = "Zusammenarbeit & Führung"
languages = "Sprachen"



[extra]
brand_text = "Felix"
name = "Felix Schlösser"
email = "info@felixschloesser.de"
image="tintin_in_shenzhen.jpg"

source_code_link = "https://github.com/felixschloesser/homepage"
source_code_licence.name = "AGPL v3"
source_code_licence.link = "https://www.gnu.org/licenses/agpl-3.0.en.html"

content_licence.name = "CC BY-NC-SA 4.0"
content_licence.link = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

cv_focus = "privacy_and_security" # or "software_engineering"

social_media = [
    { url = "https://github.com/felixschloesser/", name="Github", icon = "fab fa-github"},
    { url = "https://noc.social/@tintin", name="Mastodon", icon = "fab fa-mastodon"},
    { url = "mailto:info@felixschloesser.de", name="Mail", icon = "fas fa-envelope"},
    { url = "https://www.linkedin.com/in/felix-schl%C3%B6sser-115792292/", name = "LinkedIn", icon = "fab fa-linkedin"}
]

[extra.address]
street_name = "Mechelsestraat"
house_number = "122"
post_code = "3000"
city = "Leuven"



