base_url = "https://felixschloesser.de"
compile_sass = true
build_search_index = false

# Language Settings
default_language = "en"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[links]
# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true


[translations]

[languages.en]
# Language specific settigns
title = "Felix Schlösser"
description = "A Software Engineer currently living in Hamburg, Germany. Sometimes goes by TinTin."


[languages.en.translations]
occupation = "CS Student at Hamburg University of Technology"
by = "by"
source = "source"
source_code = "source code"
licenced_under = "licenced under"
content_licenced_under = "Contents, unless stated otherwise, under"
powered_by = "powered by"
zola_description = "a static site generator written in rust"
not_found_message = "Unfortunately this page could not be found."
back = "Back to the Homepage"
no_images = "No images found."
hire_me = "Hire me!"

since = "since"
experience = "experience"
education = "education"
skills = "skills"
thesis = "thesis"
supervisors = "supervisors"
grade = "grade"
award = "award"

linkedin_cta = "Contact me on LinkedIn"
email_cta = "Send Email"
download_cv_cta = "Download CV"
email_subject = "Job inquiry"


programming_languages = "programming languages"
tools = "tools"
soft_skills = "soft skills"
languages = "languages"
references = "References available upon request."


[languages.de]
# Language specific settigns
title = "Felix Schlösser"
description = "Ein Softwareentwickler derzeit in Hamburg lebt. In machen kontexten auch als TinTin (frz. Tim von Tim und Struppi) bekannt."


[languages.de.translations]
occupation = "Informatikstudent an der TU-Hamburg"
by = "von"
source = "Quelle"
source_code = "Quelltext"
licenced_under = "lizensiert unter der"
content_licenced_under = "Inhalte, wenn nicht anders angegeben, unter"
powered_by = "erstellt mit"
zola_description = "einem in Rust geschriebenen statischen Seitengenerator"
not_found_message = "Diese Seite konnte leider nicht gefunden werden."
back = "Zurück zur Startseite"
no_images = "Keine Bilder gefunden."
hire_me = "Stell mich ein!"
since = "seit"
experience = "Erfahrungen"
education = "Bildung"
skills = "Fähigkeiten"

thesis = "Abschlussarbeit"
supervisors = "Betreuer"
grade = "Note"
award = "Auszeichnung"

linkedin_cta = "Auf LinkedIn kontaktieren"
email_cta = "E-Mail senden"
download_cv_cta = "Lebenslauf herunterladen"
email_subject = "Jobanfrage"


programming_languages = "Programmiersprachen"
tools = "Werkzeuge"
soft_skills = "Soft Skills"
languages = "Sprachen"
references = "Referenzen können auf Anfrage zur Verfügung gestellt werden."




[extra]
# Put all your custom variables here
debug=false

brand_text = "TinTin"

name = "Felix Schlösser"
nickname = "TinTin"
image="tintin_in_shenzhen.jpg"

city="Hamburg"
copyright_year="2023"

source_code_link = "https://github.com/felixschloesser/homepage"

source_code_licence.name = "AGPL v3"
source_code_licence.link = "https://www.gnu.org/licenses/agpl-3.0.en.html"

content_licence.name = "CC BY-NC-SA 4.0"
content_licence. link = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

social_media = [
    { url = "https://github.com/felixschloesser/", name="Github", icon = "fab fa-github"},
    { url = "https://noc.social/@tintin", name="Mastodon", icon = "fab fa-mastodon"},
    { url = "mailto:info@felixschloesser.de", name="Mail", icon = "fas fa-envelope"},
    { url = "https://www.linkedin.com/in/felix-schl%C3%B6sser-115792292/", name = "LinkedIn", icon = "fab fa-linkedin"}
]

