[[images]]
url = "images/china/big-train-station.jpg"
alt_text = { en = "Picture of the waiting area of the long-distance train station in Shanghai.", de = "Foto der Wartezone des Fernbahnhofs in Shanghai." }
date = "2019-01-03"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/bikes-in-bush.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-01-03"
license = "CC BY-NC-SA 4.0"
