[[images]]
url = "images/italy/bus-depot.jpg"
alt_text = { en = "Picture of the waiting area of the long-distance train station in Shanghai.", de = "Foto der Wartezone des Fernbahnhofs in Shanghai." }
date = "2021-07-26"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/italy/village-square.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2021-07-26"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/italy/milan-station.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2021-08-01"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/italy/glacier.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2021-08-04"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/italy/glacier-tunnel.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2021-08-04"
license = "CC BY-NC-SA 4.0"
