backend:
  name: git-gateway
  branch: dev
  site_domain: felixschloesser.de
  repo: felixschloesser/homepage
  cms_label_prefix: decap-cms/

#publish_mode: editorial_workflow
media_folder: "static/images"

display_url: https://felixschloesser.de
site_url: https://felixschloesser.de
logo_url: https://felixschloesser.de/favicon.svg
locale: de

editor:
  preview: false

collections:
  - name: "landing"
    label: "Startseite"
    files:
      - name: "en"
        label: "Landing Page [EN]"
        file: "content/_index.md"
        preview_path: "/"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Image"
            name: "extra"
            widget: "object"
            fields:
              - {label: "Image", name: "image_path", widget: "image"}
              - {label: "Alt-Text", name: "image_alt", widget: "string", required: false}
              - {label: "Title", name: "image_title", widget: "string"}
              - {label: "Author", name: "image_author", widget: "string"}
              - {label: "Source", name: "image_source", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - name: "de"
        label: "Startseite [DE]"
        file: "content/_index.de.md"
        preview_path: "/cv"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Image"
            name: "extra"
            widget: "object"
            fields:
              - {label: "Image", name: "image_path", widget: "image"}
              - {label: "Alt-Text", name: "image_alt", widget: "string"}
              - {label: "Title", name: "image_title", widget: "string"}
              - {label: "Author", name: "image_author", widget: "string"}
              - {label: "Source", name: "image_source", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "cv"
    label: "Lebenslauf"
    files:
      - name: "education"
        label: "Bildung"
        file: "content/cv/education.toml"
        preview_path: "/cv"
        fields:
          - label: "Bildungsabschnitte"
            name: "education"
            widget: "list"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Organisation", name: "organisation", widget: "string"}
              - {label: "Ort [EN]", name: "location_en", widget: "string"}
              - {label: "Ort [DE]", name: "location_de", widget: "string"}
              - {label: "Startdatum", name: "start_date", widget: "datetime"}
              - {label: "Enddatum", name: "end_date", widget: "datetime", required: false}

          - label: "Abschlussarbeit"
            name: "thesis"
            widget: "object"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Zusammenfassung [EN]", name: "summary_en", widget: "text"}
              - {label: "Zusammenfassung [DE]", name: "summary_de", widget: "text"}
              - {label: "Organisation", name: "organisation", widget: "string"}
              - {label: "Abteilung", name: "department", widget: "string"}
              - {label: "Betreuer", name: "supervisors", widget: "list"}
              - {label: "Note", name: "grade", widget: "string"}
              - {label: "Schlagwörter", name: "keywords", widget: "list"}

      - name: "experience"
        label: "Berufserfahrung"
        file: "content/cv/experience.toml"
        preview_path: "/cv/"
        fields:
          - label: "Experience Entries"
            name: "experience"
            widget: "list"
            fields:
              - {label: "Title [EN]", name: "title_en", widget: "string"}
              - {label: "Title [DE]", name: "title_de", widget: "string"}
              - {label: "Description [EN]", name: "description_en", widget: "text"}
              - {label: "Description [DE]", name: "description_de", widget: "text"}
              - {label: "Organisation", name: "organisation", widget: "string"}
              - {label: "Department", name: "department", widget: "string", required: false}
              - {label: "Location [EN]", name: "location_en", widget: "string"}
              - {label: "Location [DE]", name: "location_de", widget: "string"}
              - {label: "Start Date", name: "start_date", widget: "date"}
              - {label: "End Date", name: "end_date", widget: "date"}
              - {label: "Keywords", name: "keywords", widget: "list"}
              - {label: "Award [EN]", name: "award_en", widget: "string", required: false}
              - {label: "Award [DE]", name: "award_de", widget: "string", required: false}
  - name: "photography"
    label: "Photography"
    preview_path: "/photography/{{slug}}"
    folder: "content/photography"
    media_folder: "." # Relative to the collection's folder
    create: true # Allows creation of new items
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Images", name: "images", widget: "image", allow_multiple: true}


  - name: "pages"
    label: "Legal Obligations"
    files:
      - name: "imprint"
        label: "Imprint"
        preview_path: "/{{slug}}"
        file: "content/_imprint.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}


      - name: "data-protection"
        label: "Data Protection"
        preview_path: "/{{slug}}"
        file: "content/_data_protection.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
