[[educations]]
title = "Computer Science (M.Sc.), Secure Software"
organisation = "KU Leuven"
location.en = "Belgium"
location.de = "Belgien"
start_date = "2025-09-01"

[[educations]]
title = "Computer Science (B.Sc.), Software Engineering"
organisation = "TU Hamburg"
location.en = "Germany"
location.de = "Deutschland"
start_date = "2016-10-01"
end_date = "2024-03-27"

[[educations]]
title = "Erasumus+"
organisation = "Université de Technologie de Compiègne"
location.en = "France"
location.de = "Frankreich"
start_date = "2022-02-01"
end_date = "2022-08-01"

# [[educations]]
# title = "Asian Languages and Cultures"
# organisation = "ISI Language School Tokyo"
# location.en = "Japan"
# location.de = "Japan"
# start_date = "2015-09-01"
# end_date = "2016-07-01"

[[educations]]
title = "Abitur"
organisation = "Pater Damian Sekundarschule Eupen"
location.en = "Belgium"
location.de = "Belgien"
start_date = "2009-09-01"
end_date = "2015-06-30"
