[[experience]]
title.en = "Full-Stack Web Developer and Sysadmin"
title.de = "Full-Stack-Webentwickler und Sysadmin"
description.en = """\
    Developed a custom CMS backend and frontend, as well as internal CRUD web applications. \
    Operated several on-premises services on virtual machines using Ansible; \
    including observability metrics and alerting.\
    """
description.de = """\
    Entwicklung eines custom CMS Back- und Frontends sowie interner CRUD Webanwendungen. \
    Betrieb mehrere On-Premises-Dienste auf virtuellen Maschinen mit Ansible; \
    inklusive Observability, Metriken und Alarmen.\
    """
organisation = "TU Hamburg"
department = "AStA"
location.en = "Hamburg, Germany"
location.de = "Hamburg"
start_date = "2019-10-01"
end_date = "2023-03-31"
keywords = ["Django", "Wagtail CMS", "postgresql", "nginx", "grafana", "prometheus" ]

[[experience]]
title.en = "Tutor: Python for Data Analysis"
title.de = "Tutor: Python für Datenanalyse"
description.en = """\
    Taught weekly classes for up to 20 students. Topics included everything from algorithms to \
    data analysis, visualization and machine learning. \
    """
description.de = """\
    Leitung wöchentliche Übungen für bis zu 20 Studierende. Themen umfassten alles von Algorithmen bis hin zu \
    Datenanalyse, visualisierung und maschinellem Lernen. \
    """
organisation = "TU Hamburg"
department = "Institute for Secure Cyberphysical Systems"
location.en = "Hamburg, Germany"
location.de = "Hamburg"
start_date = "2023-03-01"
end_date = "2023-07-31"
keywords = ["pandas", "matplotlib", "scikit-learn"]

[[experience]]
title.en = "Tutor: Computer Networks and Internet Security"
title.de = "Tutor: Rechnernetze und Internetsicherheit"
description.en = """\
    Developed and taught weekly Rasberry Pi based labs for up to 25 students. \
    Topics included the OSI model, network programming and IP, TLS and DNS security. \
    """
description.de = """\
    Leitung wöchentliche Laborübugen mit Raspberry Pis für bis zu 25 Studierende. Themen waren u.a. das OSI-Modell,
    Netzwerkprogrammierung und IP-, TLS- und DNS-Sicherheit.
    """
organisation = "TU Hamburg"
department = "Institute for Communication Networks"
location.en = "Hamburg, Germany"
location.de = "Hamburg"
start_date = "2018-10-01"
end_date = "2023-01-31"
keywords = ["Raspberry Pi", "wireshark", "nmap"]
award.en = "Best Tutor 2020"
award.de = "Tutor Lehrpreis 2020"


[[experience]]
title.en = "Project: User Interface for a Medical Device"
title.de = "Projekt: Benutzeroberfläche für ein Medizinprodukt"
description.en = """\
    Development and deployment of a graphical user interface for a \
    open hardware ventilator, created by a small team of volunteers. \
    Financed by the German Federal Ministry for Economic Cooperation and Development and certified by TÜV-Süd \
    for manufacturing in newly industrialized countries.\
    """
description.de = """\
    Entwicklung einer grafischen Benutzeroberfläche für ein\
    Open-Hardware-Beatmungsgerät, das von einem kleinen Team von Freiwilligen entwickelt wurde. \
    Finanziert vom Bundesministerium für wirtschaftliche Zusammenarbeit und Entwicklung und vom TÜV-Süd zertifiziert \
    für die Fertigung in Schwellenländern.\
    """
organisation = "TM Rescue-Respiration UG"
location.en = "Hamburg, Germany"
location.de = "Hamburg"
start_date = "2020-08-01"
end_date = "2022-07-28"
keywords = ["PyQt5", "Tkinter", "embedded"]


[[experience]]
title.en = "Internship: Computer Vision based Quality Control"
title.de = "Praktikum: Computer-Visions basierte Qualitätskontrolle"
description.en = """\
    Research and early development of a computer vision based industrial quality control system to identify defects in \
    glossy, curved surface, metal parts. Creation a capture setup and a dataset of 1000+ images. \
    Development of a containerized jupyter notebook based prototype using edge detection and morphological operations for feature extraction. \
    """
description.de = """\
    Erforschung und frühe Entwicklung eines computergestützten industriellen Qualitätssicherungssystems zur Identifizierung von Defekten in \
    glänzenden, gekrümmten Metalloberflächen. Erstellung eines Aufnahmesetup und eines Datensatz von 1000+ Bildern. \
    Entwicklung eines containerisierten Prototypen auf Basis eines Jupyter-Notebooks mit Kantenfindung und \
    morphologischen Operationen zur Merkmalsextraktion.\
    """
organisation = "Rongheng Information Technology Co."
location.en = "Shanghai, China"
location.de = "Shanghai, China"
start_date = "2019-07-01"
end_date = "2019-09-30"
keywords = ["scikit-image", "Pillow", "jupyter", "docker"]



