first_name = "Felix"
last_name = "Schlösser"

[address]
street_name = "Mechelsestraat"
house_number = "122"
post_code = "3000"
city = "Leuven"

[job]
desired_role = "Software Engineer / Consultant"
email = "job@felixschloesser.de"
