first_name = "Felix"
last_name = "Schlösser"

[address]
street_name = "Wolfgangsweg"
street_number = "14"
post_code = "20459"
city = "Hamburg"

[job]
role = "Software Engineer"
email = "job@felixschloesser.de"
