[[technical]]
name = "Python"
level = "advanced"
applications = [ "Web Backend", "GUI", "Data Analysis", "ML" ]

[[technical]]
name = "Linux DevOps"
level = "intermediate"
applications = [ "Ansible", "GitLab CI/CD", "prometheus"]

[[technical]]
name = "Databases"
level = "intermediate"
applications = [ "PostgreSQL", "DuckDB", "Redis", "MongoDB"]

[[technical]]
name = "System Design"
level = "intermediate"
applications = [ "DDD", "Microservices", "JAMStack"]



[[technical]]
name = "Rust"
level = "intermediate"
applications = [ "Personal Projects" ]

[[technical]]
name = "HTML / CSS (+ JS)"
level = "intermediate"
applications = [ "Client Homepages" ]

[[technical]]
name = "Haskell & C"
level = "basic"
applications = [ "University Projects" ]



[[soft]]
name_en = "Teamwork & Communication"
name_de = "Teamarbeit & Kommunikation"
contexts_en = [
  "First chair of the board of student representatives (AStA)",
  "Scout leader",
  "NGO volunteering",
]
contexts_de = [
  "Erster Vorsitzender des allgemeinen Studierendenausschusses",
  "Pfadfinderleiter",
  "Freiwilligenarbeit bei NGOs"
]



[[languages]]
name_en = "German"
name_de = "Deutsch"
level_en = "Native"
level_de = "Muttersprache"

[[languages]]
name_en = "English"
name_de = "Englisch"
level_en = "C1"
level_de = "C1"

[[languages]]
name_en = "French"
name_de = "Französisch"
level_en = "B2"
level_de = "B2"

[[languages]]
name_en = "Japanese"
name_de = "Japanisch"
level_en = "JLPT N4"
level_de = "JLPT N4"


