[[technical]]
name = "Python"
level = "advanced"
applications = [ "Web Backend", "GUI", "Data Analysis", "ML" ]

[[technical]]
name = "Linux Administration"
level = "intermediate"
applications = [ "Ansible", "vSphere", "GitLab", "grafana"]

[[technical]]
name = "DB Administration"
level = "intermediate"
applications = [ "PostgreSQL", "MySQL", "Redis"]


[[technical]]
name = "Rust"
level = "intermediate"
applications = [ "Personal Projects" ]


[[technical]]
name = "Haskell"
level = "basic"
applications = [ "University Projects"]


[[technical]]
name = "JavaScript"
level = "basic"
applications = [ "Web Frontend" ]



[[soft]]
name.en = "Teamwork & Communication"
name.de = "Teamarbeit & Kommunikation"
contexts.en = [
  "First chair of the board of student representatives (AStA)",
  "Scout leader",
  "NGO volunteering",
]
contexts.de = [
  "Erster Vorsitzender des allgemeinen Studierendenausschusses",
  "Pfadfinderleiter",
  "Freiwilligenarbeit bei NGOs"
]


[[languages]]
name.en = "German"
name.de = "Deutsch"
level.en = "Native"
level.de = "Muttersprache"

[[languages]]
name.en = "English"
name.de = "Englisch"
level.en = "C2"
level.de = "C2"

[[languages]]
name.en = "French"
name.de = "Französisch"
level.en = "C1"
level.de = "C1"


[[languages]]
name.en = "Japanese"
name.de = "Japanisch"
level.en = "JLPT N4"
level.de = "JLPT N4"


