[[images]]
url = "images/china/shanghai-train-station.jpg"
alt_text = { en = "Picture of the waiting area of the long-distance train station in Shanghai.", de = "Foto der Wartezone des Fernbahnhofs in Shanghai." }
date = "2019-08-25"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/bikes-in-bush.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-08-30"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/bikes-on-curb.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-08-30"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/carry-up.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-07"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/carry-down.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-07"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/changcha-train-station.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-01"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/cleaning-roof.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-07-27"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/components.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-08-31"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/door.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-07-27"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/electric-city.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-08-31"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/down-stairs-1.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-08-23"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/down-stairs-2.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-08-23"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/mao-bible.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-06-29"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/no-painting.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-01"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/overpass.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-01"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/painting-floor.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-01"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/paintings.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-01"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/pudong.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-06-27"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/pudong-night.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-06-28"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/radio-tower.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-07-27"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/river.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-08"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/satelite-dish.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-08-31"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/sleeper-train.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-01"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/stinky-tofu.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-07-27"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/sunrise.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-07"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/surveillance.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-08-24"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/van-goch.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-01"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/walkway.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-07"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/yellow-mountains-1.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-07"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/yellow-mountains-2.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-07"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/yellow-mountains-3.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-07"
license = "CC BY-NC-SA 4.0"

[[images]]
url = "images/china/yellow-mountains-4.jpg"
alt_text = { en = "Picture of a bike parking area in Shanghai.", de = "Foto eines Fahrradparkplatzes in Shanghai." }
date = "2019-09-07"
license = "CC BY-NC-SA 4.0"
